services:
  neo4j:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glycoproteomics-graph-tool
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - ./graph_data:/var/lib/neo4j/graph_data       # Map host ./graph_data folder to container import directory
      - ./stringDB:/var/lib/neo4j/stringDB       
      - ./bfx_databases:/var/lib/neo4j/bfx_databases       
      - ./conf:/var/lib/neo4j/conf         # Optional custom config directory
      - neo4j-data:/data                   # Persistent data storage
    environment:
      - NEO4J_AUTH=neo4j/your_password  # Set username and password
      - NEO4J_dbms_memory_heap_initial__size=1G
      - NEO4J_dbms_memory_heap_max__size=4G
      - NEO4J_dbms_memory_pagecache_size=2G
      #- NEO4JLABS_PLUGINS='["apoc"]'
volumes:
  neo4j-data:
